# Generated by Django 4.2.3 on 2023-07-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("respiration_rate", models.FloatField()),
                ("body_temperature", models.FloatField()),
                ("blood_oxygen_levels", models.FloatField()),
                ("eye_movement", models.FloatField()),
                ("hours_of_sleep", models.FloatField()),
                ("sleep_rate", models.FloatField()),
            ],
        ),
    ]
